ngpu ?= $(shell nvidia-smi -L | wc -l)
torchrun_intra = torchrun --standalone --nproc-per-node

SRC ?= csrc/bindings.cu
HEADERS := $(wildcard csrc/*.cuh) $(wildcard csrc/megakernel/*.cuh)
NVCC ?= nvcc
ARCH ?= SM103
PYTHON ?= python3
THUNDERKITTENS_ROOT ?= ./third_party/ThunderKittens
OUT ?= mok/_C$(shell $(PYTHON) -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")

# Python/PyTorch binding
PYTHON_INCLUDES ?= $(shell $(PYTHON) -c "import sysconfig; print('-I', sysconfig.get_path('include'), sep='')")
PYTORCH_INCLUDES ?= $(shell $(PYTHON) -c "from torch.utils.cpp_extension import include_paths; print(' '.join(['-I' + p for p in include_paths()]))")
PYTORCH_LIBDIR ?= $(shell $(PYTHON) -c "from torch.utils.cpp_extension import library_paths; print(' '.join(['-L' + p for p in library_paths()]))")

# NVCC flags
NVCCFLAGS := -DNDEBUG -lineinfo
NVCCFLAGS += --expt-extended-lambda --expt-relaxed-constexpr
NVCCFLAGS += -Xcompiler=-Wno-psabi -Xcompiler=-fno-strict-aliasing
NVCCFLAGS += -forward-unknown-to-host-compiler -ftemplate-backtrace-limit=0
NVCCFLAGS += -std=c++20 -lrt -lpthread -ldl -lcuda -lcudadevrt -lcudart_static
NVCCFLAGS += -O3 --use_fast_math
NVCCFLAGS += -Xnvlink=--verbose -Xptxas=--verbose -Xptxas=--warn-on-spills
NVCCFLAGS += -I${THUNDERKITTENS_ROOT}/include
NVCCFLAGS += -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__
NVCCFLAGS += -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
NVCCFLAGS += -DTORCH_API_INCLUDE_EXTENSION_H
NVCCFLAGS += -DTORCH_EXTENSION_NAME=_C
NVCCFLAGS += $(PYTHON_INCLUDES) $(PYTORCH_INCLUDES) ${PYTORCH_LIBDIR}
NVCCFLAGS += -ltorch_python -ltorch_cuda -ltorch_cpu -ltorch -lc10_cuda -lc10
NVCCFLAGS += -shared -fPIC
NVCCFLAGS += -diag-suppress 3189 # for warnings generated by PyTorch C++ headers

ifeq ($(ARCH),SM103)
NVCCFLAGS += -DKITTENS_SM103 -gencode arch=compute_103a,code=sm_103a
else ifeq ($(ARCH),SM100)
NVCCFLAGS += -DKITTENS_SM100 -gencode arch=compute_100a,code=sm_100a
else
$(error Unsupported ARCH '$(ARCH)'; expected SM100 or SM103)
endif

all: $(OUT)

test: $(OUT)
	$(PYTHON) -m torch.distributed.run --standalone --nproc-per-node=4 -m pytest -s tests/

$(OUT): $(SRC) $(HEADERS)
	$(NVCC) $(SRC) $(NVCCFLAGS) -o $(OUT)

clean:
	rm -f $(OUT)

.PHONY: all test clean

# MOK_ARCH=SM100 $(PYTHON) -m pip install -e . --no-build-isolation -vvv
# Multi-arch build is not supported yet.

build-docker-for-b200:
	docker build --no-cache -t vuiseng9/mixture-of-kittens .

# install-torch 130
install-for-b200:
	$(PYTHON) -m pip install pytest
	MOK_ARCH=SM100 $(PYTHON) setup.py build_ext --inplace

test-functional:
	$(torchrun_intra) $(ngpu) -m pytest -s tests/test_functional.py



